-- AlterTable
ALTER TABLE `character` ADD COLUMN `aggressable` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `alignmentGrade` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `alignmentSide` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `alignmentValue` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `characterPower` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `dishonor` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `energy` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `honor` INTEGER NOT NULL DEFAULT 0;
