enum PlayableBreedEnum {
	UNDEFINED = 0,
	Feca = 1,
	Osamodas = 2,
	Enutrof = 3,
	Sram = 4,
	Xelor = 5,
	Ecaflip = 6,
	Eniripsa = 7,
	Iop = 8,
	Cra = 9,
	Sadida = 10,
	Sacrieur = 11,
	Pandawa = 12,
	Roublard = 13,
	Zobal = 14,
	Steamer = 15,
	Eliotrope = 16,
	Huppermage = 17,
	Ouginak = 18,
	Forgelance = 20,
}

export const playableBreed = {
	1: "Feca",
	2: "Osamodas",
	3: "Enutrof",
	4: "Sram",
	5: "Xelor",
	6: "Ecaflip",
	7: "Eniripsa",
	8: "Iop",
	9: "Cra",
	10: "Sadida",
	11: "Sacrieur",
	12: "Pandawa",
	13: "Roublard",
	14: "Zobal",
	15: "Steamer",
	16: "Eliotrope",
	17: "Huppermage",
	18: "Ouginak",
	20: "Forgelance",
}

export default PlayableBreedEnum
