database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: ""
  name: breakEmu
authServer:
  host: 192.168.1.113
  port: 5555
worldServer:
  host: 192.168.1.113
  port: 443
debug:
  showDebugMessages: true
  showProtocolMessage: false
  showDatabaseLogs: false
dofus:
  dofusProtocolVersion: 1.0.3+7dfcc24
  versionMajor: 2
  versionMinor: 69
