-- AlterTable
ALTER TABLE `character` ADD COLUMN `AP` INTEGER NOT NULL DEFAULT 6,
    ADD COLUMN `MP` INTEGER NOT NULL DEFAULT 3,
    ADD COLUMN `agility` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `cellId` INTEGER NOT NULL DEFAULT 300,
    ADD COLUMN `chance` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `direction` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `intelligence` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `kamas` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `mapId` VARCHAR(191) NOT NULL DEFAULT '153092354',
    ADD COLUMN `prospection` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `strength` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `vitality` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `wisdom` INTEGER NOT NULL DEFAULT 0;
